export interface Model {
  id: string
  name: string
  description: string
  type: string
  category: string
  size: string
  parameters: string
  zkmlVerified: boolean
  teeAttested: boolean
  totalInferences: number
  avgAccuracy: number
  creator: string
  tags: string[]
  createdAt: string
  updatedAt: string
  license: string
  downloadCount: number
  rating: number
}

export const mockModels: Model[] = [
  // LLM Models
  {
    id: '1',
    name: 'LLaMA-7B Chat',
    description: 'Conversational AI model based on LLaMA 7B with verifiable inference on blockchain',
    type: 'LLM',
    category: 'Conversational AI',
    size: '14 GB',
    parameters: '7B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 892341,
    avgAccuracy: 91.2,
    creator: 'Meta AI',
    tags: ['llm', 'chat', 'llama', 'conversational'],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-19',
    license: 'OpenRAIL',
    downloadCount: 34521,
    rating: 4.9,
  },
  {
    id: '2',
    name: 'LLaMA-13B Instruct',
    description: 'Enhanced instruction-following model with improved reasoning capabilities',
    type: 'LLM',
    category: 'Instruction Following',
    size: '26 GB',
    parameters: '13B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 567234,
    avgAccuracy: 92.5,
    creator: 'Meta AI',
    tags: ['llm', 'instruct', 'llama', 'reasoning'],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-20',
    license: 'OpenRAIL',
    downloadCount: 28934,
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Mistral-7B Instruct',
    description: 'Efficient instruction-following LLM with zkML proofs for all inference operations',
    type: 'LLM',
    category: 'Instruction Following',
    size: '14 GB',
    parameters: '7B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 456789,
    avgAccuracy: 92.3,
    creator: 'Mistral AI',
    tags: ['llm', 'instruct', 'mistral', 'chat'],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-18',
    license: 'Apache-2.0',
    downloadCount: 28901,
    rating: 4.8,
  },
  {
    id: '4',
    name: 'Mistral-8x7B MoE',
    description: 'Mixture of Experts model with sparse activation for efficient inference',
    type: 'LLM',
    category: 'Conversational AI',
    size: '47 GB',
    parameters: '47B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 94.1,
    creator: 'Mistral AI',
    tags: ['llm', 'moe', 'mistral', 'efficient'],
    createdAt: '2024-03-01',
    updatedAt: '2024-03-21',
    license: 'Apache-2.0',
    downloadCount: 19234,
    rating: 4.9,
  },
  {
    id: '5',
    name: 'CodeLlama-13B',
    description: 'Code generation and understanding model with blockchain verification',
    type: 'LLM',
    category: 'Code Generation',
    size: '26 GB',
    parameters: '13B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 90.1,
    creator: 'Meta AI',
    tags: ['llm', 'code', 'programming', 'generation'],
    createdAt: '2024-01-30',
    updatedAt: '2024-03-17',
    license: 'CodeLlama License',
    downloadCount: 19876,
    rating: 4.9,
  },
  {
    id: '6',
    name: 'CodeLlama-34B',
    description: 'Large-scale code generation model for complex programming tasks',
    type: 'LLM',
    category: 'Code Generation',
    size: '68 GB',
    parameters: '34B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 145678,
    avgAccuracy: 91.8,
    creator: 'Meta AI',
    tags: ['llm', 'code', 'programming', 'large'],
    createdAt: '2024-02-20',
    updatedAt: '2024-03-19',
    license: 'CodeLlama License',
    downloadCount: 12345,
    rating: 4.8,
  },
  {
    id: '7',
    name: 'Falcon-40B Instruct',
    description: 'Powerful instruction-following model with full computation verification',
    type: 'LLM',
    category: 'Conversational AI',
    size: '80 GB',
    parameters: '40B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 123456,
    avgAccuracy: 93.8,
    creator: 'TII',
    tags: ['llm', 'falcon', 'chat', 'instruct'],
    createdAt: '2024-02-20',
    updatedAt: '2024-03-19',
    license: 'Apache-2.0',
    downloadCount: 15678,
    rating: 4.9,
  },
  {
    id: '8',
    name: 'Falcon-180B',
    description: 'Massive language model with state-of-the-art performance on benchmarks',
    type: 'LLM',
    category: 'Conversational AI',
    size: '350 GB',
    parameters: '180B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 67890,
    avgAccuracy: 95.2,
    creator: 'TII',
    tags: ['llm', 'falcon', 'large', 'sota'],
    createdAt: '2024-03-05',
    updatedAt: '2024-03-20',
    license: 'Apache-2.0',
    downloadCount: 8765,
    rating: 5.0,
  },
  {
    id: '9',
    name: 'Gemma-7B',
    description: 'Lightweight open model from Google with excellent performance',
    type: 'LLM',
    category: 'Conversational AI',
    size: '14 GB',
    parameters: '7B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 90.5,
    creator: 'Google',
    tags: ['llm', 'gemma', 'google', 'efficient'],
    createdAt: '2024-03-10',
    updatedAt: '2024-03-21',
    license: 'Gemma License',
    downloadCount: 23456,
    rating: 4.7,
  },
  {
    id: '10',
    name: 'Gemma-2B',
    description: 'Ultra-lightweight model for edge deployment with TEE verification',
    type: 'LLM',
    category: 'Conversational AI',
    size: '4 GB',
    parameters: '2B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 567890,
    avgAccuracy: 87.3,
    creator: 'Google',
    tags: ['llm', 'gemma', 'edge', 'lightweight'],
    createdAt: '2024-03-10',
    updatedAt: '2024-03-21',
    license: 'Gemma License',
    downloadCount: 34567,
    rating: 4.6,
  },
  {
    id: '11',
    name: 'Qwen-14B Chat',
    description: 'Multilingual chat model with strong reasoning capabilities',
    type: 'LLM',
    category: 'Conversational AI',
    size: '28 GB',
    parameters: '14B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 91.7,
    creator: 'Alibaba Cloud',
    tags: ['llm', 'qwen', 'multilingual', 'chat'],
    createdAt: '2024-02-25',
    updatedAt: '2024-03-18',
    license: 'Apache-2.0',
    downloadCount: 18765,
    rating: 4.7,
  },
  {
    id: '12',
    name: 'Qwen-72B',
    description: 'Large-scale multilingual model with exceptional performance',
    type: 'LLM',
    category: 'Conversational AI',
    size: '140 GB',
    parameters: '72B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 98765,
    avgAccuracy: 94.5,
    creator: 'Alibaba Cloud',
    tags: ['llm', 'qwen', 'large', 'multilingual'],
    createdAt: '2024-03-01',
    updatedAt: '2024-03-20',
    license: 'Apache-2.0',
    downloadCount: 9876,
    rating: 4.9,
  },

  // NLP Models
  {
    id: '13',
    name: 'GPT-2 Sentiment Analysis',
    description: 'Sentiment analysis model based on GPT-2 with zkML proofs for verifiable inference',
    type: 'NLP',
    category: 'Sentiment Analysis',
    size: '1.5 GB',
    parameters: '1.5B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 245678,
    avgAccuracy: 94.5,
    creator: 'OpenGradient Labs',
    tags: ['nlp', 'sentiment', 'gpt2', 'text-analysis'],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-18',
    license: 'MIT',
    downloadCount: 12453,
    rating: 4.8,
  },
  {
    id: '14',
    name: 'BERT Base Uncased',
    description: 'Classic BERT model for NLP tasks with full verification capabilities',
    type: 'NLP',
    category: 'Language Understanding',
    size: '440 MB',
    parameters: '110M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 2345678,
    avgAccuracy: 93.4,
    creator: 'Google AI',
    tags: ['nlp', 'bert', 'embedding', 'classification'],
    createdAt: '2023-10-05',
    updatedAt: '2024-03-15',
    license: 'Apache-2.0',
    downloadCount: 89012,
    rating: 4.9,
  },
  {
    id: '15',
    name: 'BERT Large Uncased',
    description: 'Large BERT model for complex NLP tasks requiring deep understanding',
    type: 'NLP',
    category: 'Language Understanding',
    size: '1.3 GB',
    parameters: '340M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 1234567,
    avgAccuracy: 94.8,
    creator: 'Google AI',
    tags: ['nlp', 'bert', 'large', 'embedding'],
    createdAt: '2023-10-10',
    updatedAt: '2024-03-16',
    license: 'Apache-2.0',
    downloadCount: 67890,
    rating: 4.8,
  },
  {
    id: '16',
    name: 'RoBERTa Base',
    description: 'Optimized BERT variant with improved training methodology',
    type: 'NLP',
    category: 'Language Understanding',
    size: '500 MB',
    parameters: '125M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 987654,
    avgAccuracy: 94.1,
    creator: 'Meta AI',
    tags: ['nlp', 'roberta', 'bert', 'classification'],
    createdAt: '2023-11-01',
    updatedAt: '2024-03-17',
    license: 'MIT',
    downloadCount: 54321,
    rating: 4.7,
  },
  {
    id: '17',
    name: 'DeBERTa-v3',
    description: 'Enhanced BERT with disentangled attention mechanism',
    type: 'NLP',
    category: 'Language Understanding',
    size: '800 MB',
    parameters: '184M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 654321,
    avgAccuracy: 95.2,
    creator: 'Microsoft',
    tags: ['nlp', 'deberta', 'attention', 'sota'],
    createdAt: '2024-01-05',
    updatedAt: '2024-03-18',
    license: 'MIT',
    downloadCount: 43210,
    rating: 4.8,
  },
  {
    id: '18',
    name: 'T5 Base',
    description: 'Text-to-text transfer transformer for versatile NLP tasks',
    type: 'NLP',
    category: 'Text Generation',
    size: '900 MB',
    parameters: '220M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 543210,
    avgAccuracy: 92.7,
    creator: 'Google Research',
    tags: ['nlp', 't5', 'generation', 'translation'],
    createdAt: '2023-12-01',
    updatedAt: '2024-03-15',
    license: 'Apache-2.0',
    downloadCount: 38765,
    rating: 4.6,
  },
  {
    id: '19',
    name: 'DistilBERT',
    description: 'Distilled BERT model for fast inference with minimal accuracy loss',
    type: 'NLP',
    category: 'Language Understanding',
    size: '250 MB',
    parameters: '66M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 1876543,
    avgAccuracy: 91.8,
    creator: 'Hugging Face',
    tags: ['nlp', 'distilbert', 'fast', 'efficient'],
    createdAt: '2023-09-15',
    updatedAt: '2024-03-14',
    license: 'Apache-2.0',
    downloadCount: 76543,
    rating: 4.7,
  },

  // Computer Vision Models
  {
    id: '20',
    name: 'ResNet-50 Image Classifier',
    description: 'Image classification model with TEE-attested computations for trust verification',
    type: 'Computer Vision',
    category: 'Image Classification',
    size: '98 MB',
    parameters: '25.6M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 1234567,
    avgAccuracy: 92.8,
    creator: 'Microsoft Research',
    tags: ['cv', 'classification', 'resnet', 'images'],
    createdAt: '2023-11-20',
    updatedAt: '2024-03-17',
    license: 'Apache-2.0',
    downloadCount: 56789,
    rating: 4.7,
  },
  {
    id: '21',
    name: 'ResNet-101',
    description: 'Deeper ResNet variant for more complex image classification tasks',
    type: 'Computer Vision',
    category: 'Image Classification',
    size: '170 MB',
    parameters: '44.5M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 876543,
    avgAccuracy: 93.5,
    creator: 'Microsoft Research',
    tags: ['cv', 'classification', 'resnet', 'deep'],
    createdAt: '2023-11-25',
    updatedAt: '2024-03-18',
    license: 'Apache-2.0',
    downloadCount: 45678,
    rating: 4.6,
  },
  {
    id: '22',
    name: 'EfficientNet-B7',
    description: 'State-of-the-art image classification with optimal efficiency',
    type: 'Computer Vision',
    category: 'Image Classification',
    size: '260 MB',
    parameters: '66M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 654321,
    avgAccuracy: 94.9,
    creator: 'Google',
    tags: ['cv', 'efficientnet', 'classification', 'sota'],
    createdAt: '2024-01-10',
    updatedAt: '2024-03-19',
    license: 'Apache-2.0',
    downloadCount: 34567,
    rating: 4.8,
  },
  {
    id: '23',
    name: 'ViT Base Patch16',
    description: 'Vision Transformer for image classification with TEE attestation',
    type: 'Computer Vision',
    category: 'Image Classification',
    size: '346 MB',
    parameters: '86M',
    zkmlVerified: false,
    teeAttested: true,
    totalInferences: 567123,
    avgAccuracy: 91.5,
    creator: 'Google Research',
    tags: ['cv', 'vit', 'transformer', 'classification'],
    createdAt: '2023-12-10',
    updatedAt: '2024-03-16',
    license: 'Apache-2.0',
    downloadCount: 23456,
    rating: 4.6,
  },
  {
    id: '24',
    name: 'ViT Large Patch16',
    description: 'Large Vision Transformer with enhanced accuracy for complex tasks',
    type: 'Computer Vision',
    category: 'Image Classification',
    size: '1.2 GB',
    parameters: '307M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 93.2,
    creator: 'Google Research',
    tags: ['cv', 'vit', 'transformer', 'large'],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-18',
    license: 'Apache-2.0',
    downloadCount: 19876,
    rating: 4.7,
  },
  {
    id: '25',
    name: 'YOLOv8 Object Detection',
    description: 'Real-time object detection with TEE attestation for verified computations',
    type: 'Computer Vision',
    category: 'Object Detection',
    size: '132 MB',
    parameters: '43.7M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 789012,
    avgAccuracy: 89.7,
    creator: 'Ultralytics',
    tags: ['cv', 'detection', 'yolo', 'realtime'],
    createdAt: '2024-01-22',
    updatedAt: '2024-03-19',
    license: 'AGPL-3.0',
    downloadCount: 34567,
    rating: 4.7,
  },
  {
    id: '26',
    name: 'YOLOv8x',
    description: 'Extra-large YOLO model for maximum detection accuracy',
    type: 'Computer Vision',
    category: 'Object Detection',
    size: '270 MB',
    parameters: '68.2M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 456789,
    avgAccuracy: 91.3,
    creator: 'Ultralytics',
    tags: ['cv', 'detection', 'yolo', 'large'],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-20',
    license: 'AGPL-3.0',
    downloadCount: 23456,
    rating: 4.8,
  },
  {
    id: '27',
    name: 'DETR',
    description: 'End-to-end object detection with transformers',
    type: 'Computer Vision',
    category: 'Object Detection',
    size: '160 MB',
    parameters: '41M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 90.5,
    creator: 'Meta AI',
    tags: ['cv', 'detection', 'transformer', 'detr'],
    createdAt: '2024-01-05',
    updatedAt: '2024-03-17',
    license: 'Apache-2.0',
    downloadCount: 18765,
    rating: 4.6,
  },
  {
    id: '28',
    name: 'Segment Anything (SAM)',
    description: 'Universal image segmentation model with zero-shot capabilities',
    type: 'Computer Vision',
    category: 'Image Segmentation',
    size: '2.4 GB',
    parameters: '632M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 92.1,
    creator: 'Meta AI',
    tags: ['cv', 'segmentation', 'sam', 'zero-shot'],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-19',
    license: 'Apache-2.0',
    downloadCount: 28765,
    rating: 4.9,
  },

  // Audio Models
  {
    id: '29',
    name: 'Whisper Small Transcription',
    description: 'Speech-to-text transcription with zkML proofs ensuring computational correctness',
    type: 'Audio',
    category: 'Speech-to-Text',
    size: '244 MB',
    parameters: '244M',
    zkmlVerified: true,
    teeAttested: false,
    totalInferences: 567890,
    avgAccuracy: 95.1,
    creator: 'OpenAI',
    tags: ['audio', 'transcription', 'whisper', 'speech'],
    createdAt: '2024-01-08',
    updatedAt: '2024-03-16',
    license: 'MIT',
    downloadCount: 23456,
    rating: 4.6,
  },
  {
    id: '30',
    name: 'Whisper Large-v3',
    description: 'Most accurate Whisper model for multilingual speech recognition',
    type: 'Audio',
    category: 'Speech-to-Text',
    size: '1.5 GB',
    parameters: '1.5B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 97.2,
    creator: 'OpenAI',
    tags: ['audio', 'transcription', 'whisper', 'multilingual'],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-20',
    license: 'MIT',
    downloadCount: 34567,
    rating: 4.9,
  },
  {
    id: '31',
    name: 'Wav2Vec2 Base',
    description: 'Self-supervised speech representation learning model',
    type: 'Audio',
    category: 'Speech Recognition',
    size: '360 MB',
    parameters: '95M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 456789,
    avgAccuracy: 93.8,
    creator: 'Meta AI',
    tags: ['audio', 'wav2vec', 'speech', 'representation'],
    createdAt: '2024-01-20',
    updatedAt: '2024-03-18',
    license: 'MIT',
    downloadCount: 19876,
    rating: 4.7,
  },
  {
    id: '32',
    name: 'AudioLDM',
    description: 'Text-to-audio generation model with latent diffusion',
    type: 'Audio',
    category: 'Audio Generation',
    size: '1.8 GB',
    parameters: '1.2B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 123456,
    avgAccuracy: 88.5,
    creator: 'University of Oxford',
    tags: ['audio', 'generation', 'diffusion', 'text-to-audio'],
    createdAt: '2024-02-20',
    updatedAt: '2024-03-19',
    license: 'MIT',
    downloadCount: 12345,
    rating: 4.6,
  },

  // Generative Models
  {
    id: '33',
    name: 'Stable Diffusion XL Turbo',
    description: 'Image generation model with verifiable pipeline and TEE attestation',
    type: 'Generative',
    category: 'Image Generation',
    size: '6.9 GB',
    parameters: '2.6B',
    zkmlVerified: false,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 88.5,
    creator: 'Stability AI',
    tags: ['generative', 'images', 'diffusion', 'art'],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-18',
    license: 'CreativeML Open RAIL',
    downloadCount: 45678,
    rating: 4.8,
  },
  {
    id: '34',
    name: 'Stable Diffusion 2.1',
    description: 'Classic text-to-image diffusion model with zkML verification',
    type: 'Generative',
    category: 'Image Generation',
    size: '5.2 GB',
    parameters: '1.4B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 567890,
    avgAccuracy: 87.3,
    creator: 'Stability AI',
    tags: ['generative', 'images', 'diffusion', 'text-to-image'],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-17',
    license: 'CreativeML Open RAIL',
    downloadCount: 56789,
    rating: 4.7,
  },
  {
    id: '35',
    name: 'Midjourney Alternative',
    description: 'Open-source high-quality image generation with artistic style',
    type: 'Generative',
    category: 'Image Generation',
    size: '8.5 GB',
    parameters: '3.5B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 89.8,
    creator: 'Open Source Community',
    tags: ['generative', 'images', 'art', 'creative'],
    createdAt: '2024-03-01',
    updatedAt: '2024-03-20',
    license: 'Apache-2.0',
    downloadCount: 34567,
    rating: 4.8,
  },
  {
    id: '36',
    name: 'ControlNet',
    description: 'Spatial control for diffusion models with edge/canny/depth guidance',
    type: 'Generative',
    category: 'Image Generation',
    size: '1.4 GB',
    parameters: '567M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 345678,
    avgAccuracy: 91.2,
    creator: 'Lvmin Zhang',
    tags: ['generative', 'control', 'diffusion', 'spatial'],
    createdAt: '2024-02-05',
    updatedAt: '2024-03-19',
    license: 'Apache-2.0',
    downloadCount: 28765,
    rating: 4.9,
  },

  // Multimodal Models
  {
    id: '37',
    name: 'CLIP ViT-B/32',
    description: 'Multimodal model for text-image understanding with zero-shot capabilities',
    type: 'Multimodal',
    category: 'Zero-Shot Classification',
    size: '594 MB',
    parameters: '151M',
    zkmlVerified: true,
    teeAttested: false,
    totalInferences: 678901,
    avgAccuracy: 87.9,
    creator: 'OpenAI',
    tags: ['multimodal', 'clip', 'zero-shot', 'embedding'],
    createdAt: '2023-11-15',
    updatedAt: '2024-03-14',
    license: 'MIT',
    downloadCount: 45678,
    rating: 4.7,
  },
  {
    id: '38',
    name: 'CLIP ViT-L/14',
    description: 'Large CLIP model with enhanced text-image alignment',
    type: 'Multimodal',
    category: 'Zero-Shot Classification',
    size: '1.8 GB',
    parameters: '428M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 456789,
    avgAccuracy: 90.3,
    creator: 'OpenAI',
    tags: ['multimodal', 'clip', 'large', 'embedding'],
    createdAt: '2023-12-01',
    updatedAt: '2024-03-16',
    license: 'MIT',
    downloadCount: 34567,
    rating: 4.8,
  },
  {
    id: '39',
    name: 'BLIP-2',
    description: 'Bootstrapping language-image pre-training for VQA and captioning',
    type: 'Multimodal',
    category: 'Visual Question Answering',
    size: '2.8 GB',
    parameters: '1.2B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 234567,
    avgAccuracy: 91.5,
    creator: 'Salesforce',
    tags: ['multimodal', 'blip', 'vqa', 'captioning'],
    createdAt: '2024-01-25',
    updatedAt: '2024-03-18',
    license: 'Apache-2.0',
    downloadCount: 23456,
    rating: 4.7,
  },
  {
    id: '40',
    name: 'LLaVA 13B',
    description: 'Large language and vision assistant for visual reasoning',
    type: 'Multimodal',
    category: 'Visual Question Answering',
    size: '26 GB',
    parameters: '13B',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 178654,
    avgAccuracy: 92.8,
    creator: 'University of Wisconsin',
    tags: ['multimodal', 'llava', 'vqa', 'reasoning'],
    createdAt: '2024-02-25',
    updatedAt: '2024-03-20',
    license: 'Apache-2.0',
    downloadCount: 18765,
    rating: 4.8,
  },

  // DeFi/Analytics Models
  {
    id: '41',
    name: 'OG 1hr Volatility ETH/USDT',
    description: '1-hour volatility prediction model for ETH/USDT trading pair',
    type: 'DeFi',
    category: 'Volatility Prediction',
    size: '45 MB',
    parameters: '12M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 987654,
    avgAccuracy: 86.5,
    creator: 'OpenGradient Labs',
    tags: ['defi', 'volatility', 'eth', 'prediction'],
    createdAt: '2024-01-10',
    updatedAt: '2024-03-21',
    license: 'MIT',
    downloadCount: 45678,
    rating: 4.6,
  },
  {
    id: '42',
    name: 'OG AMM Fee Optimization',
    description: 'Optimal fee calculation for AMM liquidity pools',
    type: 'DeFi',
    category: 'Fee Optimization',
    size: '32 MB',
    parameters: '8.5M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 654321,
    avgAccuracy: 88.2,
    creator: 'OpenGradient Labs',
    tags: ['defi', 'amm', 'fees', 'optimization'],
    createdAt: '2024-01-20',
    updatedAt: '2024-03-20',
    license: 'MIT',
    downloadCount: 34567,
    rating: 4.7,
  },
  {
    id: '43',
    name: 'OG 30min Return SUI/USDT',
    description: '30-minute return prediction for SUI/USDT pair',
    type: 'DeFi',
    category: 'Return Prediction',
    size: '38 MB',
    parameters: '9.8M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 543210,
    avgAccuracy: 84.7,
    creator: 'OpenGradient Labs',
    tags: ['defi', 'return', 'sui', 'prediction'],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-19',
    license: 'MIT',
    downloadCount: 28765,
    rating: 4.5,
  },
  {
    id: '44',
    name: 'ETH Volatility Oracle',
    description: 'Real-time ETH volatility oracle with on-chain verification',
    type: 'DeFi',
    category: 'Volatility Prediction',
    size: '52 MB',
    parameters: '14M',
    zkmlVerified: true,
    teeAttested: true,
    totalInferences: 432109,
    avgAccuracy: 87.3,
    creator: 'OpenGradient Labs',
    tags: ['defi', 'volatility', 'eth', 'oracle'],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-21',
    license: 'MIT',
    downloadCount: 23456,
    rating: 4.7,
  },
]

export const categories = [
  'All',
  'Conversational AI',
  'Instruction Following',
  'Code Generation',
  'Sentiment Analysis',
  'Language Understanding',
  'Text Generation',
  'Image Classification',
  'Object Detection',
  'Image Segmentation',
  'Speech-to-Text',
  'Speech Recognition',
  'Audio Generation',
  'Image Generation',
  'Zero-Shot Classification',
  'Visual Question Answering',
  'Volatility Prediction',
  'Fee Optimization',
  'Return Prediction',
]

export const modelTypes = ['All', 'LLM', 'NLP', 'Computer Vision', 'Audio', 'Generative', 'Multimodal', 'DeFi']

export const networkStats = {
  totalModels: 1523,
  totalInferences: 2145678,
  zkmlProofs: 345678,
  teeAttestations: 567890,
  activeUsers: 12456,
}
